name: aoc24

ghc-options: -Wall -threaded #-prof -fprof-auto -rtsopts

default-extensions:
  - OverloadedStrings

dependencies:
  - base == 4.*
  - attoparsec
  - bytestring
  - matrix
  - vector
  - containers
  - text
  - scientific

executables:
  aoc24:
    main: Main.hs
    dependencies:
      - aoc24

library:
  source-dirs: src
  exposed-modules:
    - Day1
    # - Day2
    # - Day3
    # - Day4
    # - Day5
    # - Day6
    # - Day7
    # - Day8
    # - Day9
    # - Day10
    # - Day11
    # - Day12
    # - Day13
    # - Day14
    # - Day15
    # - Day16
    # - Day17
    # - Day18
    # - Day19
    # - Day20
    # - Day21
    # - Day22
    # - Day23
    # - Day24
    # - Day25
